### PR TITLE
Added sign language to speech app project

### PR DESCRIPTION
**Pull request by nodamu**

### CODE REVIEW

**Review by nodamu — COMMENTED** [review]
Helping our communities with AI

**Review by sbboakye — CHANGES_REQUESTED** [review]
Please look at the format very well and put the appropriate information in square brackets and those that need to be in parenthesis in parenthesis. Look at the format carefully and only change the text.

**Comment by nodamu** [comment]
Made the changes

**Review by sbboakye — CHANGES_REQUESTED** [review]
You left out the project description. Write a description about your project like you did in the first commit

**Comment by nodamu** [comment]
Added the project description

**Review by sbboakye — APPROVED** [review]
Awesome work.

**Pull request merged**
